// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type OauthClient struct {
	ID       int32
	ClientID uuid.UUID
	Secret   string
	Domain   string
}

type User struct {
	ID         int32
	Name       string
	Email      string
	Password   string
	VerifiedAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
