// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Oauth2Token struct {
	ID        int64
	CreatedAt time.Time
	ExpiresAt time.Time
	Code      string
	Access    string
	Refresh   string
	Data      json.RawMessage
}

type OauthClient struct {
	ID       int32
	ClientID uuid.UUID
	Secret   string
	Domain   string
}

type User struct {
	ID         int32
	Name       string
	Email      string
	Password   string
	VerifiedAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
