// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: oauth2_tokens.sql

package database

import (
	"context"
	"encoding/json"
)

const getDataByValidAccessToken = `-- name: GetDataByValidAccessToken :one
SELECT "data" FROM oauth2_tokens WHERE access = $1 AND expires_at > NOW() LIMIT 1
`

func (q *Queries) GetDataByValidAccessToken(ctx context.Context, access string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getDataByValidAccessToken, access)
	var data json.RawMessage
	err := row.Scan(&data)
	return data, err
}
